############################################
# Global settings for the application
############################################

namespace: sample-namespace
createNamespace: false

app:
  name: sample-app
  image: juanroldan1989/sample-image:0.0.1
  port: 5000

############################################
# Deployment settings
############################################

replicaCount: 3
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

############################################
# Rollout configuration
############################################

rollout:
  enabled: false # Deployment resource is created and rollout is not
  # enabled: true # Rollout resource is created and deployment is not

############################################
# Probe configuration
############################################

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

############################################
# HPA configuration
############################################

hpa:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

############################################
# Ingress configuration (external apps)
############################################

ingress:
  enabled: false  # Set to true for external access
  ingressClassName: alb
  host: ""        # Optional, e.g., "sample.example.com"
  path: "/"       # Default path
  pathType: "Prefix"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health

############################################
# Network policy configuration
############################################

networkPolicy:
  enabled: false         # set to true to enable network policy
  name: sample-ingress-policy
  appLabel: app-1        # app label to match
  allowedAppLabel: app-2 # app label to allow traffic from

############################################
# ResourceQuota configuration for the namespace
############################################

resourceQuota:
  enabled: false
  cpu: "20"      # Maximum CPU allowed in the namespace
  memory: "20Gi" # Maximum memory allowed
  pods: "50"     # Maximum number of pods

############################################
# Secrets configuration
############################################

secrets:
  enabled: false
