apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-infrastructure
  namespace: argocd
  # This finalizer ensures the application is not deleted until all child
  # resources are deleted. It helps prevent orphaned resources, but deletion
  # can take longer or block if a child resource is stuck.
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/juanroldan1989/platform.git
    targetRevision: main
    path: argo/1-infrastructure
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
