controller:
  service:
    annotations:
      metallb.universe.tf/address-pool: default
    type: LoadBalancer
  ingressClassResource:
    default: true

nameOverride: ingress-nginx
fullnameOverride: ingress-nginx
namespaceOverride: ingress-nginx
