nameOverride: ingress-nginx
fullnameOverride: ingress-nginx
namespaceOverride: ingress-nginx

controller:
  ingressClassResource:
    default: true

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/civo-loadbalancer-protocol: http

admissionWebhooks:
  enabled: false
