apiVersion: v1
kind: Namespace
metadata:
  name: hello-{{ .Values.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-{{ .Values.name }}
  namespace: hello-{{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hashicorp/http-echo
          args:
            - "-text=👋 Hello from {{ .Values.name }}.automatalife.com"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello-{{ .Values.name }}
  namespace: hello-{{ .Values.name }}
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-{{ .Values.name }}
  namespace: hello-{{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - app.{{ .Values.name }}.automatalife.com
        - hello.automatalife.com
      secretName: wildcard-tls
  rules:
    - host: app.{{ .Values.name }}.automatalife.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-{{ .Values.name }}
                port:
                  number: 80
    - host: hello.automatalife.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-{{ .Values.name }}
                port:
                  number: 80
