{{- $secretItems := dict }}
{{- range .Values.env }}
  {{- if .secret }}
    {{- $_ := set $secretItems .name . }}
  {{- end }}
{{- end }}

{{- if gt (len $secretItems) 0 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secretstore-sample
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-secret
    creationPolicy: Owner
  data:
    {{- range $name, $item := $secretItems }}
    - secretKey: {{ $item.secretKey }}
      remoteRef:
        key: {{ $item.secretName }}
        property: {{ $item.secretKey }}
    {{- end }}
{{- end }}
