apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: london-infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  providerConfigRef:
    name: london
  forProvider:
    source: Remote
    module: git::https://github.com/juanroldan1989/platform.git//terraform/modules/civo_cluster?ref=main
    vars:
    - key: cluster_name
      value: london
    - key: node_count
      value: "3"
    - key: node_type
      value: "g4s.kube.medium"
