# This ClusterSecretStore configuration allows External Secrets Operator (ESO)
# to access AWS Secrets Manager or Parameter Store for managing secrets across clusters.
# It is designed to be used in the management cluster,
# enabling centralized secret management for all workload clusters.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore
spec:
  provider:
    aws:
      service: SecretsManager            # or ParameterStore for AWS Parameter Store - https://external-secrets.io/latest/provider/aws-parameter-store/
      region: us-east-1                  # AWS region where the secrets are stored
      auth:
        secretRef:                       # secretRef is used to authenticate with AWS Secrets Manager / Parameter Store
          accessKeyIDSecretRef:          # accessKeyIDSecretRef/secretAccessKeySecretRef are used to authenticate with AWS
            name: aws-creds
            key: access-key
            namespace: external-secrets  # Namespace where the `aws-creds` secret is located
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key
            namespace: external-secrets

# TODO: use sealed secret values from crossplane-secrets secret instead of aws-creds
# TODO: then remove aws-creds secret from bootstrap script