---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgANhMqCnxzVYqt6/B5zaLLy5Us5zeHJbig/7Pl5S4K5q9gs5tlW/thnuKvnlhNYaF80nQs38ViiicCQSXlMHiIq49h722DlunENcSPnloqqGJZy990QfUcoYg7joFFoq0MLQUB6HHpsLg6yJ1RPLRHPWq539tebAgV9v5T2SvPWWDtNm0Wnqj2c2Yqu8gL9zudjjuUaLfsUdZ/KWbua0YR+AtKEPm9TNOvjMIMoyuXmv+Qp0PWAQGuBdy/c7hFb+9NwFRWTZ1SRzKDSSACkhC2XhW/JlEq6enQjI6u+dIC9Fmw1+47X7FzE1tNyJoHIrCxnFcP0b9iu77J8kF8i/RFvIZVVSvhr94rm6G6myyHvZM0H1ib/bkAIYOQw6YdpxqyhitY3uWhxmefpk+VeVRIdCccyTKKs8H+hwoi4DreST9pj+zXYTLPOroiF/ht9aQex5bft7+1gmW9n7CWxXxyY8hzGN6AeTsMTvsJK7EvYvazY7SkrRT4m/mgTAHDXvyWkmRnX/ipvz+qvZtfAfOo1NF5Haqh6UwPkVxWZr7Qjn3q0lGS1WMOCQgpbOxOWGEpFJo9mdtK0f069a3EYlAnQu5hIF0afotVjlSCP9B1K7QeeAp/MDA8IJ22iw44/1/RwL27KHmyQbvDKgsrXxm4SwJbRPPg2+dSKm1vPWd8+xUhpAo5sZabyWJYeDqzxdFcnqy3u0u0I5/DL/ceLQEjf4QetuTLPlpjMILNfGyzdyLjkJq7uwEhT
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
