provider: cloudflare
policy: sync
domainFilters:
  - automatalife.com
txtOwnerId: newyork

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: CLOUDFLARE_API_TOKEN

extraArgs:
  - --registry=txt
  - --source=service
  - --source=ingress
