# This enables you to define high-level cluster requests as ClusterClaim resources.
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeclusters.platform.devops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  group: platform.devops
  names:
    kind: CompositeCluster
    plural: compositeclusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    clusterName:
                      type: string
                    nodeCount:
                      type: integer
                    nodeType:
                      type: string
                  required:
                    - clusterName
                    - nodeCount
                    - nodeType
