apiVersion: platform.devops/v1alpha1
kind: ClusterClaim
metadata:
  name: london
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  compositionSelector:
    matchLabels:
      provider: civo
      cluster: k3s
  parameters:
    clusterName: london
    nodeCount: 1
    nodeType: g4s.kube.large
