apiVersion: batch/v1
kind: Job
metadata:
  name: london-infrastructure-wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: wait
        image: bitnami/kubectl:1.25.12
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            name=$(kubectl get workspace -l cluster-name=london -o jsonpath='{.items[0].metadata.name}')
            if [ -n "$name" ]; then
              echo "Waiting for workspace $name to be ready"
              if kubectl wait --for=condition=Ready workspace/$name; then
                echo "Cluster provisioned"
                break
              fi
            else
              echo "Workspace not yet created"
            fi
            sleep 5
          done
      restartPolicy: Never
  backoffLimit: 1
