apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-support
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
  template:
    metadata:
      name: cert-manager-support-{{name}}
      annotations:
        argocd.argoproj.io/description: "Additional resources for Cert Manager in {{name}} cluster"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/juanroldan1989/platform.git
          targetRevision: main
          path: registry/clusters/workload/support/cert-manager
          helm:
            valueFiles:
              - $values/registry/clusters/overlays/{{name}}/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: '{{name}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
