apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true" # TODO: also allow to filter by cluster, apps use ingress with HTTPS
  template:
    metadata:
      name: hello-world-app-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy Hello World App into {{name}} cluster"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/juanroldan1989/platform'
        targetRevision: main
        path: registry/clusters/{{name}}/apps
      destination:
        name: '{{name}}'
        namespace: hello
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true

