apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
    - clusters:
        selector:
          matchLabels:
            in-cluster: "true"
  template:
    metadata:
      name: ingress-nginx-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploys ingress-nginx to {{name}} cluster for external traffic routing"
    spec:
      project: default
      destination:
        name: '{{name}}'
        namespace: 'ingress-nginx'
      sources:
        - repoURL: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          targetRevision: 4.12.3
          helm:
            valueFiles:
              - $values/registry/clusters/{{name}}/ingress-nginx/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
