apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kube-system
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.15.3
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        service:
          type: ClusterIP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
