apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            in-cluster: "true"
  template:
    metadata:
      name: sealed-secrets-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy Sealed Secrets in {{name}} cluster"
    spec:
      project: default
      sources:
        - repoURL: https://bitnami-labs.github.io/sealed-secrets
          chart: sealed-secrets
          targetRevision: 2.15.3
          helm:
            values: |
              fullnameOverride: sealed-secrets-controller
              service:
                type: ClusterIP
      destination:
        name: '{{name}}'
        namespace: 'kube-system'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
