# TODO: values passed already via values.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-lb-secrets-external-secret
  namespace: crossplane-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: cloudflare-lb-secrets    # <== final K8s Secret name
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-account-id
      remoteRef:
        key: cloudflare-lb-secrets # <== Name of the AWS Secrets Manager secret
        property: cloudflare-account-id
    - secretKey: cloudflare-zone-id
      remoteRef:
        key: cloudflare-lb-secrets
        property: cloudflare-zone-id
    - secretKey: cloudflare-notification-email
      remoteRef:
        key: cloudflare-lb-secrets
        property: cloudflare-notification-email
