apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/juanroldan1989/platform
    targetRevision: main
    path: registry/clusters/mgmt/apps
    directory:
      include: argocd-ingress.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
