# ESO PushSecret - Push database credentials to AWS Secrets Manager
# This runs in the management cluster and pushes the DB credentials created by Terraform
# to AWS Secrets Manager so that workload clusters can access them.
#
# Note: The secret keys here must match what's stored in the Kubernetes secret
# created by the Terraform module (blog-db-managed-creds)
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .Values.name }}-database-push
  namespace: {{ .Values.database.target_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 1m
  secretStoreRefs:
    - name: cluster-secretstore
      kind: ClusterSecretStore
  selector:
    secret:
      name: blog-db-managed-creds
  data:
    - match:
        secretKey: username           # From civo_database.db.username
        remoteRef:
          remoteKey: civo/blog-database-credentials
          property: username
    - match:
        secretKey: password           # From civo_database.db.password
        remoteRef:
          remoteKey: civo/blog-database-credentials
          property: password
    - match:
        secretKey: host              # From civo_database.db.endpoint (stored as 'host' in secret)
        remoteRef:
          remoteKey: civo/blog-database-credentials
          property: host
    - match:
        secretKey: port              # From civo_database.db.port
        remoteRef:
          remoteKey: civo/blog-database-credentials
          property: port
    - match:
        secretKey: database          # From var.database_name (stored as 'database' in secret)
        remoteRef:
          remoteKey: civo/blog-database-credentials
          property: database
    - match:
        secretKey: connection_string  # Constructed connection string
        remoteRef:
          remoteKey: civo/blog-database-credentials
          property: connection_string
