# Wait job to ensure database infrastructure is provisioned before proceeding with the next steps
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-database-infrastructure-wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: wait
        image: bitnami/kubectl:1.25.12
        command:
        - /bin/sh
        - -c
        - |
          while ! kubectl wait --for=jsonpath='{.status.conditions[0].status}'='True' workspace/{{ .Values.name }}-database-infrastructure; do echo "waiting for database to provision"; sleep 5; done
      restartPolicy: Never
  backoffLimit: 1
