# Frankfurt Cluster Configuration

## Kubernetes cluster configuration for Frankfurt cluster
# cloud_provider:
#   civo:
#     enabled: true # Temporarily disabled for simplicity purposes

global:
  name: frankfurt
  region: fra1
  k8s_version: 1.30.5-k3s1
  node_count: "1"
  node_type: g4s.kube.large

## DNS Configuration for External DNS
txtOwnerId: frankfurt
domainFilters:
  - automatalife.com

## Cert Manager Configuration
# This section defines the wildcard certificate for the Frankfurt cluster.
# A wildcard certificate will be created for all namespaces listed under `namespaces`.
cert_manager:
  wildcard:
    enabled: true
    namespaces:
      - cert-manager
      - hello-frankfurt
      - blog-frankfurt
