# Civo Cluster Provider Configuration
# This provider configuration is used to connect to Civo and manage resources using Terraform.
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.global.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-{{ .Values.global.name }}"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }

      required_providers {
        civo = {
          source = "civo/civo"
          version = "1.1.0"
        }

        kubernetes = {
          source = "hashicorp/kubernetes"
          version = "2.23.0"
        }
      }
    }

    provider "civo" {
      region = "{{ .Values.global.region }}"
    }
  credentials:
    - filename: gen-nothing
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: crossplane-secrets
        key: CIVO_TOKEN
