# ESO configuration to sync blog database credentials from AWS Secrets Manager
# This will be deployed to each workload cluster via ArgoCD
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blog-db-credentials
  namespace: blog-db
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: blog-db-managed-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: username
    remoteRef:
      key: civo/blog-database-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: civo/blog-database-credentials
      property: password
  - secretKey: host
    remoteRef:
      key: civo/blog-database-credentials
      property: host
  - secretKey: port
    remoteRef:
      key: civo/blog-database-credentials
      property: port
  - secretKey: database
    remoteRef:
      key: civo/blog-database-credentials
      property: database
  - secretKey: connection_string
    remoteRef:
      key: civo/blog-database-credentials
      property: connection_string
