apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blog-db-creds
  namespace: blog-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: blog-db-creds
    creationPolicy: Owner
  data:
    - secretKey: mysql-username
      remoteRef:
        key: platform/databases/blog-db
        property: username
    - secretKey: mysql-password
      remoteRef:
        key: platform/databases/blog-db
        property: password
    - secretKey: mysql-root-password
      remoteRef:
        key: platform/databases/blog-db
        property: root_password
