apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: platform-infrastructure
    platform.dev/layer: infrastructure
    platform.dev/category: security
    platform.dev/tool: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
  template:
    metadata:
      name: cert-manager-{{name}}
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: security
        app.kubernetes.io/part-of: platform-infrastructure
        platform.dev/layer: infrastructure
        platform.dev/category: security
        platform.dev/cluster: "{{name}}"
      annotations:
        argocd.argoproj.io/description: "Deploys Cert Manager in {{name}} cluster for managing certificates"
    spec:
      project: infrastructure
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.14.3
        helm:
          parameters:
            - name: installCRDs
              value: "true"
      destination:
        name: '{{name}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
