apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.name }}
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-{{ .Values.name }}"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }

      required_providers {
        cloudflare = {
          source = "cloudflare/cloudflare"
          version = "5.6.0"
        }
      }
    }

    provider "cloudflare" {
      api_token = var.cloudflare_api_token
    }
  credentials:
    - filename: gen-nothing
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: crossplane-secrets
        key: TF_VAR_cloudflare_api_token
