apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: name-app
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: environment
          operator: In
          values:
          - dev
          - test
          - prod
  template:
    metadata:
      name: '{{name}}-name-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/juanroldan1989/platform'
        targetRevision: main
        path: applications/base # Path to the base application
        helm:
          valueFiles:
            - ../name-app/values-{{metadata.labels.environment}}.yaml
      destination:
        server: '{{server}}' # Server URL of the cluster
        namespace: name-app  # Application resources deployed here
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
