# This file is used to define the configuration for the London cluster.

# Kubernetes cluster configuration for London region.
name: london
region: lon1
k8s_version: 1.29.8-k3s1
node_count: "1"
node_type: g4s.kube.large

# DNS Configuration for External DNS
txtOwnerId: london
domainFilters:
  - automatalife.com

# Cert Manager Configuration
# This section defines the wildcard certificate for the London cluster.
# A wildcard certificate will be created for all namespaces listed under `namespaces`.
cert_manager:
  wildcard:
    enabled: true
    namespaces:
      - cert-manager
      - hello-london
      # - goodbye-london
