# London Cluster Configuration

## Kubernetes cluster configuration for London cluster
cloud_provider:
  civo:
    enabled: true

global:
  name: london
  region: lon1
  k8s_version: 1.30.5-k3s1
  node_count: "1"
  node_type: g4s.kube.large
  storage_class: civo-volume

## DNS Configuration for External DNS
txtOwnerId: london
domainFilters:
  - automatalife.com

## Cert Manager Configuration
# This section defines the wildcard certificate for London cluster.
# A wildcard certificate will be created for all namespaces listed under `namespaces`.
cert_manager:
  wildcard:
    enabled: true
    namespaces:
      - cert-manager
      - hello-london
      - blog-db
