apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator-support
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
    - clusters:
        selector:
          matchLabels:
            in-cluster: "true"
  template:
    metadata:
      name: external-secrets-operator-support-{{name}}
      annotations:
        argocd.argoproj.io/description: "Additional resources for ESO in {{name}} cluster"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/juanroldan1989/platform'
        targetRevision: main
        path: registry/clusters/workload/support/eso
        directory:
          recurse: true
      destination:
        name: '{{name}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
