apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
    - clusters:
        selector:
          matchLabels:
            in-cluster: "true"
  template:
    metadata:
      name: external-secrets-operator-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy & Configuration of ESO (External Secrets Operator) in {{name}} cluster for managing Secrets"
    spec:
      project: default
      sources:
        - repoURL: https://charts.external-secrets.io
          chart: external-secrets
          targetRevision: 0.15.1
          helm:
            valueFiles:
              - $values/registry/clusters/workload/config/eso/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: '{{name}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
