apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
    - clusters:
        selector:
          matchLabels:
            in-cluster: "true"
  template:
    metadata:
      name: external-dns-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy & Configuration of External DNS in {{name}} cluster for managing DNS records"
    spec:
      project: default
      sources:
        - repoURL: https://kubernetes-sigs.github.io/external-dns/
          chart: external-dns
          targetRevision: 1.14.3
          helm:
            valueFiles:
              - $values/registry/clusters/overlays/{{name}}/values.yaml
              - $values/registry/clusters/workload/config/external-dns/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: '{{name}}'
        namespace: 'external-dns'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

# TODO: it works OK, I've added an overlay for 'in-cluster' clusters,
# but makes provision.yaml to try to create another 'in-cluster' cluster,
# try to setup a specific external-dns-config.yaml for 'in-cluster' and remove the overlay
