apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: platform-infrastructure
    platform.dev/layer: infrastructure
    platform.dev/category: networking
    platform.dev/tool: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
    - clusters:
        selector:
          matchLabels:
            in-cluster: "true"
  template:
    metadata:
      name: ingress-nginx-{{name}}
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/component: networking
        app.kubernetes.io/part-of: platform-infrastructure
        platform.dev/layer: infrastructure
        platform.dev/category: networking
        platform.dev/cluster: "{{name}}"
      annotations:
        argocd.argoproj.io/description: "Deploy & Configuration of INGRESS NGINX in {{name}} cluster for external traffic routing"
    spec:
      project: infrastructure
      sources:
        - repoURL: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          targetRevision: 4.12.3
          helm:
            valueFiles:
              - $values/registry/clusters/workload/config/ingress-nginx/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: '{{name}}'
        namespace: 'ingress-nginx'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
