provider: cloudflare
policy: sync
domainFilters:
  - automatalife.com
txtOwnerId: london

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: cloudflare-api-token
