apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: prod-cluster-control-plane
spec:
  replicas: 1
  version: v1.32.2
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: prod-cluster-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          enable-admission-plugins: NodeRestriction
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
