apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: config-clusters
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
  template:
    metadata:
      name: 'config-{{name}}'
    spec:
      project: default
      destination:
        name: in-cluster
        namespace: argocd
      source:
        repoURL: https://github.com/juanroldan1989/platform
        targetRevision: main
        path: registry/clusters/workload/config
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
