apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: london
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/juanroldan1989/platform.git
    path: registry/clusters/london
    targetRevision: main
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
