apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-secrets
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
  template:
    metadata:
      name: 'secrets-{{name}}'
    spec:
      project: default
      destination:
        name: '{{name}}'
        namespace: external-dns
      source:
        repoURL: https://github.com/juanroldan1989/platform
        targetRevision: main
        path: registry/clusters/workload/secrets
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
