# NewYork Cluster Configuration

## Kubernetes cluster configuration for NewYork cluster
# cloud_provider:
  # vultr:
    # enabled: true # Temporarily disabled until Vultr cloud provider allows for Kubernetes clusters

global:
  name: newyork
  region: "ewr"
  node_count: "1"
  node_type: "vc2-2c-4gb"
  min_nodes: "1"
  max_nodes: "3"

## DNS Configuration for External DNS
txtOwnerId: newyork
domainFilters:
  - automatalife.com

## Cert Manager Configuration
# This section defines the wildcard certificate for the NewYork cluster.
# A wildcard certificate will be created for all namespaces listed under `namespaces`.
cert_manager:
  wildcard:
    enabled: true
    namespaces:
      - cert-manager
      - hello-newyork
      - blog-newyork
