apiVersion: v1
kind: Namespace
metadata:
  name: blog-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: blog-db
data:
  config.yml: |
    port: 3000
    bindIP: 0.0.0.0
    db:
      type: postgres
      host: '$(DB_HOST)'
      port: $(DB_PORT)
      user: '$(DB_USER)'
      pass: '$(DB_PASS)'
      db: '$(DB_NAME)'
      ssl: true
      sslOptions:
        auto: false
        rejectUnauthorized: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-db
  namespace: blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: blog-db-managed-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: blog-db-managed-creds
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: blog-db-managed-creds
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: blog-db-managed-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: blog-db-managed-creds
                  key: database
          volumeMounts:
            - name: blog-config
              mountPath: /wiki/config.yml
              subPath: config.yml
      volumes:
        - name: blog-config
          configMap:
            name: blog-config
---
apiVersion: v1
kind: Service
metadata:
  name: blog-db
  namespace: blog-db
spec:
  selector:
    app: blog
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress-{{ .Values.global.name }}
  namespace: blog-db
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - blog.{{ .Values.global.name }}.automatalife.com
        - blog.automatalife.com
      secretName: wildcard-tls
  rules:
    - host: blog.{{ .Values.global.name }}.automatalife.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-db
                port:
                  number: 80
    - host: blog.automatalife.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-db
                port:
                  number: 80
