apiVersion: v1
kind: Namespace
metadata:
  name: blog-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: blog-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- if .Values.global.storage_class }}
  storageClassName: {{ .Values.global.storage_class }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-db
  namespace: blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghost:5-alpine
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: http://blog.automatalife.com
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: blog-db-london-mysql.blog-db.svc.cluster.local
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: blog-db-creds
                  key: mysql-username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: blog-db-creds
                  key: mysql-password
            - name: database__connection__database
              value: ghost_db
          volumeMounts:
            - name: content
              mountPath: /var/lib/ghost/content
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: blog-content
---
apiVersion: v1
kind: Service
metadata:
  name: blog-db
  namespace: blog-db
spec:
  selector:
    app: blog
  ports:
    - port: 80
      targetPort: 2368
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress-{{ .Values.global.name }}
  namespace: blog-db
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - blog.{{ .Values.global.name }}.automatalife.com
        - blog.automatalife.com
      secretName: wildcard-tls
  rules:
    - host: blog.{{ .Values.global.name }}.automatalife.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-db
                port:
                  number: 80
    - host: blog.automatalife.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-db
                port:
                  number: 80
