apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blog-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/diff-options: |
      IgnoreExtraneous
spec:
  generators:
    - git:
        repoURL: https://github.com/juanroldan1989/platform.git
        revision: main
        directories:
          - path: registry/databases/overlays/*
  template:
    metadata:
      name: database-for-{{path.basename}}
      annotations:
        argocd.argoproj.io/description: "Provision Managed DB for {{path.basename}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/juanroldan1989/platform.git
          targetRevision: main
          path: registry/databases/provision
          helm:
            valueFiles:
              - $values/registry/databases/overlays/{{path.basename}}/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: in-cluster
        namespace: blog-db
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
