apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blog-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/diff-options: |
      IgnoreExtraneous
spec:
  generators:
    - git:
        repoURL: https://github.com/juanroldan1989/platform.git
        revision: main
        directories:
          - path: registry/databases/overlays/*
  template:
    metadata:
      name: db-{{path.basename}}-civo-managed
      labels:
        app.kubernetes.io/name: civo-managed-database
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: platform
        platform.layer: database
        platform.category: managed-database
        platform.provider: civo
        platform.database: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/description: "CIVO Managed Database for {{path.basename}} application"
        argocd.argoproj.io/sync-wave: "20"
    spec:
      project: databases
      sources:
        - repoURL: https://github.com/juanroldan1989/platform.git
          targetRevision: main
          path: registry/databases/provision
          helm:
            valueFiles:
              - $values/registry/databases/overlays/{{path.basename}}/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: in-cluster
        namespace: blog-db
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
