apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: newyork
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-newyork"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }

      required_providers {
        vultr = {
          source = "vultr/vultr"
          version = "2.22.1"
        }

        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "2.23.0"
        }
      }
    }

    provider "vultr" {
      api_key = var.vultr_token
    }
  credentials:
    - filename: gen-nothing
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: crossplane-secrets
        key: VULTR_TOKEN
