{{- if .Values.cert_manager.wildcard.enabled -}}
{{- $root := . -}}
{{- range .Values.cert_manager.wildcard.namespaces }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: {{ . }}
spec:
  secretName: wildcard-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - '*.{{ $root.Values.name }}.automatalife.com'
---
{{- end -}}
{{- end -}}
