# For non-production environments
# no rate limits apply
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    email: automatalife@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-staging-private-key
    solvers:
      - dns01:
          cloudflare:
            email: automatalife@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: cloudflare-api-token
        selector: {}
