apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
  template:
    metadata:
      name: observability-jaeger-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy Jaeger trace backend and UI in {{name}} cluster"
    spec:
      project: default
      sources:
        - repoURL: https://jaegertracing.github.io/helm-charts
          chart: jaeger
          targetRevision: 4.11.1
          helm:
            valueFiles:
              - $values/registry/clusters/workload/config/observability/jaeger-values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: "{{name}}"
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
