apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-gpu-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "47"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: "true"
            gpu: "true"
  template:
    metadata:
      name: observability-gpu-metrics-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy NVIDIA DCGM exporter GPU metrics in {{name}} cluster"
    spec:
      project: default
      sources:
        - repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
          chart: dcgm-exporter
          targetRevision: 4.8.2
          helm:
            valueFiles:
              - $values/registry/clusters/workload/config/observability/gpu-metrics-values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: "{{name}}"
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
