apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            # cluster: "london"
            workload: "true"
  template:
    metadata:
      name: blog-in-{{name}}
      annotations:
        argocd.argoproj.io/description: "Deploy Blog (Ghost) App in {{name}} cluster"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/juanroldan1989/platform.git
          targetRevision: main
          path: registry/apps/blog
          helm:
            valueFiles:
              - $values/registry/clusters/overlays/{{name}}/values.yaml
        - repoURL: https://github.com/juanroldan1989/platform
          targetRevision: main
          ref: values
      destination:
        name: '{{name}}'
        namespace: blog-{{name}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
