apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-terraform-provider
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: crossplane-system
  source:
    repoURL: https://github.com/juanroldan1989/platform.git
    targetRevision: main
    path: bootstrap/crossplane
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
